### ISSUE TITLE
Error when saving spike arrays from model that was ran twice 

### ISSUE THREAD

**Issue by cmazzio** [abuzarmahmood/pytau#36]
See model database and script for saving spike arrays below. When running saving_tau.py for CM43_Test2_qhcl (taste 2), I get the following error:

![Screenshot from 2024-06-15 14-22-28](https://github.com/abuzarmahmood/pytau/assets/143443066/e7313992-c40a-4455-b870-b2dcfddfd006)

[model_database.csv](https://github.com/user-attachments/files/15849353/model_database.csv)

**Comment by cmazzio** [comment]
Oh wait here's the saving_tau.py script
[saving_tau.txt](https://github.com/user-attachments/files/15849359/saving_tau.txt)

**Comment by abuzarmahmood** [comment]
So it seems like the script is running all the way to the end (line 65) and breaking at the saving part. My guess is that you might not have the directory setup where it is trying to save the numpy file.

Try adding the following right before where the saving begins (right before line 65) and make sure that the path it is trying to save the file exists. If the folder does not exist, you have to make it either manually or in the script before the file can be saved there
`print('/media/cmazzio/large_data/Change_point_models/'+exp_name[0]+'/'+exp_name[0]+'_'+model_id[0]+'_scaled_mode_tau.npy')`

**Comment by cmazzio** [comment]
![Screenshot from 2024-06-15 15-01-13](https://github.com/abuzarmahmood/pytau/assets/143443066/dcc2cec3-0c4d-4c2b-8105-f974f7527ca1)

**Comment by abuzarmahmood** [comment]
Ok, that makes sense. Because there are multiple models which pass your conditions (table below),  you have multiple paths so it's probably having trouble generating the save path correctly.

The rows below are what I'm left with after the above conditions. It might help to add the below lines to remove duplicates [[LINK to lines](https://github.com/abuzarmahmood/pytau/blob/d0a2d6e697579bc934ae802a26a41fd2fa059e33/pytau/how_to/scripts/fit_with_fit_handler.py#L53C1-L54C38)]

```
fit_database.drop_duplicates()
fit_database.clear_mismatched_paths()
```

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/abuza/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/abuza/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


preprocess.time_lims | preprocess.bin_width | preprocess.data_transform | preprocess.preprocessor_name | model.states | model.fit | model.samples | model.model_kwargs | model.model_template_name | model.inference_func_name | data.data_dir | data.basename | data.animal_name | data.session_date | data.taste_num | data.laser_type | data.region_name | exp.exp_name | exp.model_id | exp.save_path | exp.fit_date | module.pymc3_version | module.theano_version
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[2000, 4000] | 50 | None | preprocess_single_taste | 4 | 40000 | 20000 | {'None': None} | single_taste_poisson | advi_fit | /media/cmazzio/large_data/CM43/CM43_CTATest2_h2o_nacl_qhcl_240412_123531 | CM43_CTATest2_h2o_nacl_qhcl_240412_123531 | CM43 | 123531 | 2 |   | gc1 | CM43_CTATest2_QHCl | 1003eda3 | /media/cmazzio/large_data/Change_point_models/CM43_CTATest2_QHCl/CM43_CTATest2_QHCl_1003eda3 | 6/2/2024 | 3.9.3 | 1.0.5
[2000, 4000] | 50 | None | preprocess_single_taste | 4 | 40000 | 20000 | {'None': None} | single_taste_poisson | advi_fit | /media/cmazzio/large_data/CM43/CM43_CTATest2_h2o_nacl_qhcl_240412_123531 | CM43_CTATest2_h2o_nacl_qhcl_240412_123531 | CM43 | 123531 | 2 |   | gc1 | CM43_CTATest2_QHCl | 1c282bc0 | /media/cmazzio/large_data/Change_point_models/CM43_CTATest2_QHCl/CM43_CTATest2_QHCl_1c282bc0 | 6/2/2024 | 3.9.3 | 1.0.5
[2000, 4000] | 50 | None | preprocess_single_taste | 3 | 40000 | 20000 | {'None': None} | single_taste_poisson | advi_fit | /media/cmazzio/large_data/CM43/CM43_CTATest2_h2o_nacl_qhcl_240412_123531 | CM43_CTATest2_h2o_nacl_qhcl_240412_123531 | CM43 | 123531 | 2 |   | gc1 | CM43_CTATest2_QHCl | 0a018752 | /media/cmazzio/large_data/Change_point_models/CM43_CTATest2_QHCl/CM43_CTATest2_QHCl_0a018752 | 6/2/2024 | 3.9.3 | 1.0.5
[2000, 4000] | 50 | None | preprocess_single_taste | 3 | 40000 | 20000 | {'None': None} | single_taste_poisson | advi_fit | /media/cmazzio/large_data/CM43/CM43_CTATest2_h2o_nacl_qhcl_240412_123531 | CM43_CTATest2_h2o_nacl_qhcl_240412_123531 | CM43 | 123531 | 2 |   | gc1 | CM43_CTATest2_QHCl | 98dc7b91 | /media/cmazzio/large_data/Change_point_models/CM43_CTATest2_QHCl/CM43_CTATest2_QHCl_98dc7b91 | 6/2/2024 | 3.9.3 | 1.0.5



</body>

</html>

But because you have 2 models for 2 different numbers of states, you will have to add a constraint for what number of states you want, and then you have to add something to your code to pick only one of them (unless duplicates are otherwise deleted). I've added code to the file below that SHOULD do that.

[saving_tau_updated.txt](https://github.com/user-attachments/files/15849485/saving_tau_updated.txt)

Here is a visualization of the additions.
![image](https://github.com/abuzarmahmood/pytau/assets/12436309/e6bcfe18-d825-4cd0-a932-a7842ef7154c)

Let me know if you still get errors.

**Comment by cmazzio** [comment]
Thanks so much! I tried running the updated file (I just changed wanted states to 4, not 3) and I got this error:
![Screenshot from 2024-06-15 15-28-45](https://github.com/abuzarmahmood/pytau/assets/143443066/fe8274f6-e493-4c53-b20e-19794505266a)

**Comment by abuzarmahmood** [comment]
Another edit. I didn't see the script already had something to deal with duplicates. We're already doing that in the previous edit when we select only the first row of the wanted frame. Try again and see what happens. Also added a print statement to facilitate potential future debugging.

[saving_tau_updated_2.txt](https://github.com/user-attachments/files/15850979/saving_tau_updated_2.txt)

![image](https://github.com/abuzarmahmood/pytau/assets/12436309/e2899ea0-800c-4d2e-907a-f940105a6adc)

**Comment by cmazzio** [comment]
I just got this error now:

![Screenshot from 2024-06-15 15-42-41](https://github.com/abuzarmahmood/pytau/assets/143443066/cb07d5c5-c5d2-43b2-88ae-b85e9a152814)

**Comment by abuzarmahmood** [comment]
The original script was meant to extract the changepoint values and spike train _en masse_ from a bunch of arrays (which I also failed to notice when we started editing this script). But now it will only work extract items from a single model at a time.

[saving_tau_updated_3.txt](https://github.com/user-attachments/files/15853472/saving_tau_updated_3.txt)

![image](https://github.com/abuzarmahmood/pytau/assets/12436309/fd497dbe-1394-4be1-a6b2-fec3b2448eb5)

**Comment by cmazzio** [comment]
I got this error initially, but it seemed like it was just for the print statement so I commented it out and ran again and got the error in the next comment.
![Screenshot from 2024-06-15 16-07-20](https://github.com/abuzarmahmood/pytau/assets/143443066/ae0c4c54-052d-4ef4-9e7c-70403e9922ce)

**Comment by cmazzio** [comment]
latest error after commenting out print(num) statement 
![Screenshot from 2024-06-15 16-08-42](https://github.com/abuzarmahmood/pytau/assets/143443066/1945c164-ed58-4119-ad28-55e35a6ef642)

**Comment by cmazzio** [comment]
This seems like maybe it's an issue again with my saving file lines?

**Comment by abuzarmahmood** [comment]
Yeah, I think if you get rid of the `[0]`s in the save_path, it should work (i.e. `exp_name[0]` --> `exp_name`, and `model_id[0]` --> `model_id`) because those variables are no longer lists, but are strings now
